### ISSUE TITLE
Add beforeEach, afterEach functions

### ISSUE THREAD

**Issue by kupriyanenko** [kupriyanenko/astrobench#1]
Create the global `beforeEach` and `afterEach` functions. As the name implies the `beforeEach` function is called once before each bench in the suite is run and the `afterEach` function is called once after each bench.

**Comment by prantlf** [comment]
The current global functions `setup` and `after` already work like `beforeEach` and `afterEach` around each benchmark. It is confusing. You could better rename them to `beforeEach` and `afterEach` and introduce `beforeAll` and `afterAll` on the suite level.
